### ISSUE TITLE
update rpm ostree status and verify role to use json_query

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic-host-tests#230]
The current rpm ostree status and verify roles check assumes only two deployments while setting the booted deployment fact.  With livefs, there can be three deployments so its probably a good idea to update these roles to use json_query.

It will probably look something like:
```

- name: Get rpm-ostree status output
  command: rpm-ostree status --json
  register: ros_status

- name: Import JSON
  set_fact:
    ros_json: "{{ ros_status | from_json }}"

- name: Get matching list entry
  set_fact:
    booted_deployment: "{{ item }}"
  with_items: "{{ ros_json | json_query(query) }}"
  vars:
    query: "[?booted=='true']"
```
Then the individual properties can be grabbed using booted_deployment['checksum'], booted_deployment['origin'], etc.  This needs to be compatible with the tests that use the role already unless all the tests are updated also.
