### ISSUE TITLE
Missing org_id and activationkey lookup for redhat subscription

### ISSUE THREAD

**Issue by guillaumevincent** [projectatomic/atomic-host-tests#249]
Hello,

I got an issue with actual tests. I running `improved-sanity-test` against a `RHEL-Atomic-7.4` virtual machine. My virtual machine is already activated.

So I got one question:

 * Why are we trying to run the `subscription-manager` against a machine with an active subscription?
   If we want to force the subscription to be sure the `subscription-manager` works, could we move this to another test?

If this is not possible, could we fix `roles/redhat_subscription/tasks/main.yml` to lookup for `org_id` and `activationkey` also.

I need to be able to activate my Red Hat subscription with `org_id` and `activationkey` only.

Thanks

**Comment by guillaumevincent** [comment]
My first idea to solve this issue is the following code

```
- name: get RHSM variables
  set_fact:
    RHSM_USERNAME: "{{ lookup('csvfile', 'username file={} delimiter=,'.format(subscription_file)) }}"
    RHSM_PASSWORD: "{{ lookup('csvfile', 'password file={} delimiter=,'.format(subscription_file)) }}"
    RHSM_ACTIVATION_KEY: "{{ lookup('csvfile', 'activationkey file={} delimiter=,'.format(subscription_file)) }}"
    RHSM_ORG_ID: "{{ lookup('csvfile', 'org_id file={} delimiter=,'.format(subscription_file)) }}"
    RHSM_BASE_URL: "{{ lookup('csvfile', 'baseurl file={} delimiter=,'.format(subscription_file)) }}"
    RHSM_SERVER_URL: "{{ lookup('csvfile', 'serverurl file={} delimiter=,'.format(subscription_file)) }}"

- name: Register with subscription-manager with username and password
  redhat_subscription:
    state: present
    force_register: true
    rhsm_baseurl: '{{ RHSM_BASE_URL }}'
    server_hostname: '{{ RHSM_SERVER_URL }}'
    username: '{{ RHSM_USERNAME }}'
    password: '{{ RHSM_PASSWORD }}'
  when: RHSM_USERNAME != "" and RHSM_PASSWORD != ""


- name: Register with subscription-manager with activationkey and org_id
  redhat_subscription:
    state: present
    force_register: true
    rhsm_baseurl: '{{ RHSM_BASE_URL }}'
    server_hostname: '{{ RHSM_SERVER_URL }}'
    activationkey: '{{ RHSM_ACTIVATION_KEY }}'
    org_id: '{{ RHSM_ORG_ID }}'
  when: RHSM_ACTIVATION_KEY != "" and RHSM_ORG_ID != ""
```
