### ISSUE TITLE
i-s-t repetitiveness

### ISSUE THREAD

**Issue by ashcrow** [projectatomic/atomic-host-tests#298]
There is some repetitiveness in the i-s-t suite. Consider moving things which are done multiple times into their own role OR playbook which gets included more than once.

**Comment by miabbott** [comment]
Definitely not doubting you here, but could you provide an example that stuck out to you?

**Comment by ashcrow** [comment]
Sure. Quick example:

```
    # Compare 'atomic host status' and 'rpm-ostree status' again
    - role: atomic_host_status_verify
      stop_daemon: true
      tags:
        - atomic_host_status_verify

    # Re-subscribe
    - role: redhat_subscription
      when: ansible_distribution == 'RedHat'
      tags:
        - redhat_subscription

    # Verify correct SELinux labels again
    - role: selinux_verify
      tags:
        - selinux_verify
```

Instead of doing the same sets 2x they could be part of one test suite role.
